name: Issue Triage

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  triage:
    permissions:
      issues: write
    uses: aws/aws-durable-execution-ci/.github/workflows/issue-triage.yml@71259cf476e37255752d8f9445a1a48ec92be1df
