name: Notify Slack - Release

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      release_url:
        required: true
        type: string

permissions: {}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send release notification to Slack
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_RELEASE }}
          webhook-type: incoming-webhook
          payload: |
            {
              "tag_name": "${{ inputs.tag_name }}",
              "release_url": "${{ inputs.release_url }}",
              "package_name": "${{ github.repository }}"
            }
